name = "halo-hub-submissions"
main = "src/index.ts"
compatibility_date = "2024-05-20"

[vars]
ALLOWED_ORIGINS = "https://tymai-dev.github.io,https://halohub.com"

[[d1_databases]]
binding = "DB"
database_name = "halo_hub"
database_id = "37c3f2ed-ce26-488c-9df4-8a8e39a36fca"
