name = "halo-hub-submissions"
main = "src/index.ts"
compatibility_date = "2024-05-20"

[vars]
ALLOWED_ORIGINS = "https://tymai-dev.github.io,https://halohub.com"

[[d1_databases]]
binding = "DB"
database_name = "halo_hub_submissions"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
